# Generated by Django 5.2 on 2025-06-04 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'abstract': False,
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Наименование рецепта')),
                ('text', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Введите значение больше или равное 1', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1!'), django.core.validators.MaxValueValidator(limit_value=43200, message='Максимальное значение не может превышать 30 дней (43200 минут)!')], verbose_name='Время приготовления в минутах')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-created_at',),
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество ингредиентов не может быть меньше 1!'), django.core.validators.MaxValueValidator(limit_value=1000, message='Количество ингредиентов не может быть больше 1000!')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент в составе рецепта',
                'verbose_name_plural': 'Ингредиенты в составе рецептов',
                'default_related_name': 'recipe_ingredients',
            },
        ),
    ]
