# Generated by Django 5.2 on 2025-06-02 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите значение больше или равное 1', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1!'), django.core.validators.MaxValueValidator(limit_value=43200, message='Максимальное значение не может превышать 30 дней (43200 минут)!')], verbose_name='Время приготовления в минутах'),
        ),
    ]
